# Generated by Django 3.2.6 on 2021-09-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_service_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='layers', max_length=100, verbose_name='nom de l icon du site https://feathericons.com/'),
            preserve_default=False,
        ),
    ]
