# Generated by Django 3.2.6 on 2021-09-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Petit text'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Petit text'),
        ),
    ]
