# Generated by Django 3.2.6 on 2021-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='la citation')),
                ('actif', models.BooleanField(default=True)),
                ('autor', models.CharField(max_length=100, verbose_name='')),
                ('function', models.CharField(max_length=100, verbose_name='')),
                ('image', models.ImageField(upload_to='images/', verbose_name='')),
            ],
        ),
    ]
