# Generated by Django 3.2.6 on 2021-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
