# Generated by Django 3.2.6 on 2021-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210923_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='images/clients')),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='function',
            field=models.CharField(max_length=100, verbose_name='Fonction'),
        ),
    ]
