# Generated by Django 3.2.6 on 2021-09-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210923_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Petit text'),
        ),
    ]
