# Generated by Django 3.2.6 on 2021-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Petit text'),
        ),
    ]
