# Generated by Django 3.2.6 on 2022-01-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211112_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=300, verbose_name='Description')),
                ('client_rc', models.CharField(max_length=300, verbose_name='Description')),
                ('client_nif', models.CharField(max_length=300, verbose_name='Description')),
                ('client_art', models.CharField(max_length=300, verbose_name='Description')),
                ('client_adresse', models.CharField(max_length=300, verbose_name='Description')),
                ('invoice_number', models.IntegerField(verbose_name='Numéro de facture')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Crée')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Réduction')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice', verbose_name='Facture')),
            ],
        ),
    ]
