# Generated by Django 3.2.6 on 2022-02-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(default='inter.taki@gmail.com', max_length=300, verbose_name='Email Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_phone',
            field=models.CharField(default='0550 1800 600', max_length=300, verbose_name='Téléphone Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invioce_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.CharField(max_length=300, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_adresse',
            field=models.CharField(max_length=300, verbose_name='Adresse Client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_art',
            field=models.CharField(max_length=300, verbose_name="Numéro d'article du client"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_nif',
            field=models.CharField(max_length=300, verbose_name='Nif Client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_rc',
            field=models.CharField(max_length=300, verbose_name='RC Client'),
        ),
    ]
