# Generated by Django 3.2.6 on 2021-10-07 06:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='analytics',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Google Analytics'),
        ),
        migrations.AddField(
            model_name='business',
            name='analytics2',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Analytics 2'),
        ),
        migrations.AddField(
            model_name='business',
            name='messenger',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Facebook Messenger'),
        ),
        migrations.AddField(
            model_name='business',
            name='pixel',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Facebook Pixel'),
        ),
    ]
