# Generated by Django 3.2.6 on 2022-01-18 08:00

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20211007_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='messenger_script',
            field=markdownx.models.MarkdownxField(default='herlo'),
            preserve_default=False,
        ),
    ]
