# Generated by Django 3.2.6 on 2022-01-18 08:42

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_messenger_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='analytics',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Google Analytics'),
        ),
        migrations.AlterField(
            model_name='business',
            name='analytics2',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Analytics 2'),
        ),
        migrations.AlterField(
            model_name='business',
            name='messenger',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Facebook Messenger'),
        ),
        migrations.AlterField(
            model_name='business',
            name='pixel',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Facebook Pixel'),
        ),
    ]
