# Generated by Django 3.2.6 on 2022-01-18 10:30

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20220118_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tag_body',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Google tag manager body'),
        ),
        migrations.AddField(
            model_name='business',
            name='tag_header',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Google tag manager header'),
        ),
    ]
